Hello, I am  2
Hello, I am  0
Hello, I am  1
data sent to node 1
data received on node 1 from node 0
data sent to node 2
data received on node 2 from node 0
[[], [], []]
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 1.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]]) torch.Size([1354, 1433])
tensor([[   0,    0,    0,  ..., 2550, 2550, 2550],
        [ 360, 1081, 2617,  ...,   97,  341,  825]]) torch.Size([2, 6270])
world size 3
request nodes: 0
request nodes: 0
Traceback (most recent call last):
  File "GCN_Cora_Distributed_MulNode.py", line 182, in <module>
    main(rank, world_size, host_addr_full)
  File "GCN_Cora_Distributed_MulNode.py", line 168, in main
    _, pred = model(data).max(dim=1)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "GCN_Cora_Distributed_MulNode.py", line 133, in forward
    x = self.conv1(x, edge_index)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "GCN_Cora_Distributed_MulNode.py", line 19, in forward
    return self.propagate(edge_index, size=(x.size(0), x.size(0)), x=x)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch_geometric/nn/conv/message_passing.py", line 310, in propagate
    size, kwargs)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch_geometric/nn/conv/message_passing.py", line 202, in __collect__
    j if arg[-2:] == '_j' else i)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch_geometric/nn/conv/message_passing.py", line 171, in __lift__
    return src.index_select(self.node_dim, index)
IndexError: index out of range in self
[[], [0, 2, 3, 4, 6, 7, 8, 10, 11, 17, 18, 26, 27, 29, 36, 37, 38, 40, 42, 48, 50, 55, 59, 60, 62, 64, 68, 70, 71, 72, 74, 77, 81, 87, 90, 93, 97, 98, 99, 100, 110, 113, 118, 119, 121, 122, 124, 126, 132, 137, 142, 145, 150, 151, 153, 156, 157, 162, 168, 175, 177, 180, 181, 190, 196, 197, 206, 212, 213, 214, 216, 218, 219, 225, 232, 235, 236, 240, 244, 247, 250, 253, 254, 256, 257, 258, 261, 263, 265, 266, 274, 279, 282, 284, 285, 286, 294, 295, 298, 301, 303, 304, 308, 313, 316, 320, 322, 325, 327, 328, 331, 333, 334, 336, 341, 342, 343, 346, 347, 350, 351, 355, 356, 365, 373, 375, 377, 379, 385, 389, 394, 400, 401, 403, 407, 408, 409, 410, 411, 412, 416, 417, 420, 421, 424, 425, 426, 427, 428, 429, 446, 459, 470, 471, 473, 474, 475, 476, 478, 485, 488, 492, 494, 497, 502, 505, 510, 521, 525, 534, 538, 545, 548, 553, 554, 555, 559, 568, 574, 578, 580, 583, 588, 589, 597, 598, 600, 603, 607, 608, 615, 616, 617, 618, 620, 621, 629, 631, 634, 635, 638, 644, 647, 654, 656, 658, 659, 665, 666, 667, 675, 676], [680, 683, 692, 694, 699, 700, 701, 703, 704, 707, 715, 716, 718, 729, 731, 732, 739, 740, 742, 744, 745, 749, 754, 755, 761, 764, 775, 776, 782, 783, 785, 787, 788, 792, 794, 796, 802, 805, 808, 810, 815, 821, 825, 827, 832, 841, 846, 849, 850, 853, 854, 858, 865, 866, 874, 875, 876, 880, 885, 889, 891, 892, 894, 895, 899, 902, 903, 904, 909, 912, 913, 914, 923, 924, 931, 934, 936, 943, 954, 955, 957, 961, 963, 966, 967, 968, 971, 974, 975, 976, 978, 981, 983, 985, 989, 991, 995, 997, 1002, 1003, 1004, 1005, 1010, 1017, 1020, 1029, 1032, 1035, 1040, 1042, 1048, 1050, 1069, 1070, 1071, 1081, 1084, 1087, 1092, 1096, 1099, 1100, 1104, 1108, 1109, 1111, 1113, 1114, 1116, 1119, 1130, 1141, 1142, 1143, 1146, 1147, 1148, 1149, 1150, 1165, 1166, 1167, 1168, 1174, 1181, 1182, 1183, 1187, 1193, 1197, 1198, 1202, 1205, 1217, 1223, 1225, 1233, 1234, 1243, 1248, 1254, 1265, 1269, 1274, 1277, 1278, 1285, 1286, 1298, 1301, 1302, 1309, 1310, 1311, 1312, 1314, 1315, 1324, 1327, 1330, 1338, 1339, 1346, 1348, 1349, 1350, 1351, 1352, 1353]]
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]]) torch.Size([1354, 1433])
tensor([[   0,    2,    3,  ..., 2550, 2550, 2550],
        [2617, 1488, 2636,  ...,  341,  825, 2551]]) torch.Size([2, 5518])
world size 3
request nodes: 212
Traceback (most recent call last):
  File "GCN_Cora_Distributed_MulNode.py", line 182, in <module>
    main(rank, world_size, host_addr_full)
  File "GCN_Cora_Distributed_MulNode.py", line 168, in main
    _, pred = model(data).max(dim=1)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "GCN_Cora_Distributed_MulNode.py", line 113, in forward
    requested_nodes_list = recv_object(src = 1)
  File "/home/dsys2352/DSassignment/GCN/utils.py", line 284, in recv_object
    dist.recv(size, src=src)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 850, in recv
    pg.recv([tensor], src, tag).wait()
RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:575] Connection closed by peer [10.141.0.2]:41904
Traceback (most recent call last):
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/dsys2352/miniconda3/envs/dist_GNN/bin/python', '-u', 'GCN_Cora_Distributed_MulNode.py']' returned non-zero exit status 1.
Killing subprocess 1095973
srun: error: node002: task 1: Exited with exit code 1
Traceback (most recent call last):
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/dsys2352/miniconda3/envs/dist_GNN/lib/python3.6/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/dsys2352/miniconda3/envs/dist_GNN/bin/python', '-u', 'GCN_Cora_Distributed_MulNode.py']' returned non-zero exit status 1.
Killing subprocess 290420
srun: error: node024: task 2: Exited with exit code 1
